#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn build || 
(
    echo '✖ ✖ ✖  Your current build has failed. View the errors above to see why.'
    false
)

echo '✔ ✔ ✔  Build complete, build check success. Pushing code to remote!'
